### ISSUE TITLE
JS already had classes before ES6, `new` is not all that new.

### ISSUE THREAD

**Issue by minecrawler** [joshburgess/not-awesome-es6-classes#7]
JS always had classes before. They just look a bit different:

    function MyClass() {
      this.foo = function() { console.log('Foo'); }
    }

    var myObj = new MyClass();
    myObj.foo();

Keywords, like `new` have existed for quite a while in JS. To be precise, it has been there since JS 1.0: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/new

You can still use composition with objects derived from classes made in a factory. It's not exclusive.

Also, since I am very sure you do not know, yet, `syntactical sugar` means: Write something differently (mostly shorter and more pleasing), but still do the same: https://en.wikipedia.org/wiki/Syntactic_sugar

So your whole rant is just based on ignorance and now used by other people as a basis for confusion. Please stop that.

**Comment by joshburgess** [comment]
No ignorance here other than yours, buddy. 

1. Your first example is not a class. You're conceptually treating it as a class in your head, likely based off of your familiarity with class-based programming languages like Java. It's a function using the constructor pattern to assign properties to instances of its self invoked by the 'new' keyword. This is only one of many ways to do things like this in JavaScript and one I happen to find rather ugly. Read about factory functions and Kyle Simpson's OOLO (Objects Linked to Other Objects) concept.

2. I never said the 'new' keyword was a new addition to the language. This is either poor reading comprehension on your part or extreme arrogance. Read the linked articles & books. Many of them are from well before ES6 existing and discuss the uglyness and downsides of 'new' heavily. Are you familiar with the political reasons for why JavaScript includes Java in its name? or why it has any of the similarities to Java (or sometimes its C ancestry) it has? I'm guessing you aren't.

3. What are you basing this on? To assume that I don't know what the phrase "syntactic sugar" means is completely asinine. ES6 classes are syntactic sugar for a very specific use of prototypal inheritance in JavaScript which amounts to a pseudo-classical style by using the constructor pattern and the 'new' keyword. This method pretends to be about classes, but really is just a poor & brittle form of delegation modeled after classical inheritance. This typically is the favored approach of Java and C# programmers attempting to force their knowledge of other languages into JavaScript instead of taking the time to learn about more elegant & flexible alternatives the language already supports.

Your points are weak and your tone is highly annoying. It's obvious that you either didn't read much of the linked content or just have very poor reading comprehension. Otherwise, you'd realize there are some very smart and well known people in the JavaScript community, including authors of well-respected books, who completely disagree with you. Closed.
